#:import COLORS main.COLORS

<AppCardWidget>:
    orientation: "vertical"
    size_hint_y: None
    height: dp(96)
    padding: dp(6)
    spacing: dp(4)

    Image:
        id: icon
        source: root.icon_path if root.icon_path else "assets/default_icon.png"
        size_hint_y: None
        height: dp(56)
        allow_stretch: True
        keep_ratio: True
        canvas.before:
            Color:
                rgba: COLORS["surface_light"]
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [dp(14)]

    Label:
        text: root.app_name
        color: COLORS["text"]
        font_size: "12sp"
        size_hint_y: None
        height: dp(30)
        shorten: True
        shorten_from: "right"
        halign: "center"
        valign: "top"
        text_size: self.size
